function ExcelInput1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  EXCELINPUT1 = IMPORTFILE1(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a string array.
%
%  EXCELINPUT1 = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  EXCELINPUT1 = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ExcelInput1 = importfile1("C:\Users\rober\OneDrive - Nexus365\Codes\ExcelInput.xlsx", "ExampleSetting1", [1, 31]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 15-Nov-2020 13:14:13

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 31];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "C" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = "VarName3";
opts.VariableTypes = "string";

% Specify variable properties
opts = setvaropts(opts, "VarName3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName3", "EmptyFieldRule", "auto");

% Import the data
ExcelInput1 = readmatrix(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "C" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readmatrix(workbookFile, opts, "UseExcel", false);
    ExcelInput1 = [ExcelInput1; tb]; %#ok<AGROW>
end

end